# Generated by Django 3.2.5 on 2022-08-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=False, max_length=50)),
            ],
        ),
    ]
