# Generated by Django 3.2.5 on 2022-08-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_verify',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.signup')),
                ('tokken', models.CharField(max_length=150)),
                ('verify', models.BooleanField(default=False)),
            ],
        ),
    ]
