# Generated by Django 3.2.5 on 2022-08-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_token_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='token_verify',
            name='user_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.signup'),
        ),
        migrations.AlterField(
            model_name='token_verify',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
