# Generated by Django 3.2.5 on 2022-08-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220803_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_verify',
            name='user_id',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.signup'),
        ),
    ]
