# Generated by Django 3.2.5 on 2022-08-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_token_verify_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_verify',
            name='user_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.signup'),
        ),
    ]
