# Generated by Django 3.2.5 on 2022-08-03 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_token_verify_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token_verify',
            name='id',
        ),
        migrations.AlterField(
            model_name='token_verify',
            name='user_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.signup'),
        ),
    ]
